name: Docker build of binary Debian package

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile.debian --tag yq-debian:$(date +%s)
